name: Publish ${package_name} to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  build-n-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install pypa/setuptools
        run: >-
          python -m
          pip install wheel
      - name: Extract tag name
        id: tag
        run: |
          tag=$(echo $GITHUB_REF | cut -d / -f 3)
          echo "TAG_NAME=$tag" >> $GITHUB_OUTPUT 
      - name: Update version in setup.py
        run: >-
          sed -i "s/{{PACKAGE_VERSION}}/${{ steps.tag.outputs.TAG_NAME }}/g" setup.py
      - name: Build source and wheel distributions
        run: |
          python -m pip install --upgrade build twine
          python setup.py sdist bdist_wheel
          python -m build
          twine check --strict dist/*
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

